### PR TITLE
Better reverse proxy support when using multiple proxies

### PR DESCRIPTION
**Pull request by blueliquiddesigns**

### CODE REVIEW

**Comment by benjaminpick** [comment]
What is your use case? Are both servers within your infrastructure?

"Since it is easy to forge an X-Forwarded-For field the given information should be used with care. The last IP address is always the IP address that connects to the last proxy, which means it is the most reliable source of information." (https://en.wikipedia.org/wiki/X-Forwarded-For)

**Comment by blueliquiddesigns** [comment]
Hi Ben,

When using multiple reverse proxies - like Cloudflare in front of Varnish or Nginx on the server - the X-Forwarded-For field contains multiple IPs - x.x.x.x, y.y.y.y. Currently both IPs are being passed to the Geo IP function and it will return nothing. The proposed fix accounts for this behaviour and correctly selects the last IP (i.e the first IP in the X-Forwarded-For string).

**Comment by benjaminpick** [comment]
In this case, yet it would be the first IP. However the first IP could also be a local or forged IP in case the client also uses a proxy. So would need an UI for checking "this IP is a proxy I trust, because it belongs to my network setup."

**Comment by blueliquiddesigns** [comment]
Better an IP than no IP I would think.

**Comment by benjaminpick** [comment]
It depends. Sometimes "no IP" is better than a "wrong IP". E.g. if you 
need to check the origin country for law enforcement.

Mit freundlichen Grüßen,

Benjamin Pick
Web-Entwickler

-----------------------------------------------------------------
YELLOW TREE
AGENTUR FÜR DESIGN UND KOMMUNIKATION
-----------------------------------------------------------------
T  +49 (0) 271 703019 - 5
F  +49 (0) 271 703019 - 8
B.PICK@YELLOWTREE.DE <mailto:B.PICK@YELLOWTREE.DE>
WWW.YELLOWTREE.DE
-----------------------------------------------------------------
SANDSTRASSE 173, 57072 SIEGEN
-----------------------------------------------------------------





Rafflenbeul und Utsch GbR
Rechtsform: Gesellschaft des bürgerlichen Rechts
Gesellschafter:
Heiko Rafflenbeul und Andreas Utsch
Sitz der Gesellschaft: Siegen, Deutschland
Steuer-Nr.: 342 5827 0518
-----------------------------------------------------------------

Diese E-Mail enthaelt vertrauliche oder rechtlich
geschuetzte Informationen.Wenn Sie nicht der
beabsichtigte Empfaenger sind, informieren Sie
bitte sofort den Absender und loeschen Sie diese
E-Mail. Das unbefugte Kopieren dieser E-Mail oder
die unbefugte Weitergabe der enthaltenen
Informationen ist nicht gestattet.

The information contained in this message is
confidential or protected by law.If you are not the
intended recipient, please contact the sender and
delete this message. Any unauthorised copying
of this message or unauthorised distribution of the
information contained herein is prohibited.

Am 20.02.2015 um 09:35 schrieb blueliquiddesigns:

**Comment by blueliquiddesigns** [comment]
I see your point when accuracy is concerned for legal requirements but if that's the case I certainly wouldn't be relying on MaxMind's GeoLite database - I'd be using their paid service to detect things like if a user is behind a proxy, or for fraud purposes (and in that case I would still always want an IP). 

If the software's target really this sort of market? I would have thought it would be used to give developers a general idea of a user's location to personalise / tailor their service / product.

Also, whether this patch is applied or not the current system is already exposed to clients sending forged, spoofed or proxied IPs. If as a client I use a proxy the IP isn't being passed to the X-Forwarded-For header, it will go to the REMOTE_ADDR (and you'd be doing a lookup on a 'fake' IP). And if the server I was on used a reverse proxy like Cloudflare that 'fake' proxied IP will still be passed to the X-Forwarded-For header. 

In any case, what I am trying to say is the current system penalises **legitimate** users when behind two reverse proxies. This simple patch will resolve that. The security implications regarding fake or real IP addresses is really hear nor there.

**Comment by benjaminpick** [comment]
I will use the last IP for now and a a "list of trusted proxy IPs" later.

**Comment by benjaminpick** [comment]
trusted ips can now be configured as an WP option "geoip-detect-trusted_proxy_ips". There is no UI yet, so as a workaround you can set the comma-seperated list manually in the database.

**Pull request merged**
